# Generated by Django 5.1.3 on 2024-11-11 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
