# Generated by Django 5.1.3 on 2024-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Publish")],
                default=0,
                help_text="Set the status of the post to draft or publish.",
                verbose_name="Post Status",
            ),
        ),
    ]
